import Review from '../models/Review'
import sequelize from './db-config'

const addReviews = async() => {
    try {
        await sequelize.sync()
        
        await Review.bulkCreate([
            {
                name_user: "Alice Johnson",
                email_user: "alicejohnson@example.com",
                services: 4,
                locations: 5,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Amazing tour experience with breathtaking views. Highly recommended!",
                averageGrade: 0,
                createdAt: "2023-05-12",
                tourId: 1
              },
              {
                name_user: "Bob Smith",
                email_user: "bobsmith@example.com",
                services: 3,
                locations: 4,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 3,
                message: "The tour was good, but the price was a bit high for the services provided.",
                averageGrade: 0,
                createdAt: "2023-06-15",
                tourId: 1
              },
              {
                name_user: "Charlie Brown",
                email_user: "charliebrown@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 4,
                message: "Fantastic experience overall, with friendly guides and stunning landscapes.",
                averageGrade: 0,
                createdAt: "2023-07-22",
                tourId: 2
              },
              {
                name_user: "Diana Prince",
                email_user: "dianaprince@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "The food was excellent, and the locations were beautiful. Would recommend!",
                averageGrade: 0,
                createdAt: "2023-08-30",
                tourId: 2
              },
              {
                name_user: "Ethan Hunt",
                email_user: "ethanhunt@example.com",
                services: 5,
                locations: 5,
                amenities: 5,
                prices: 2,
                food: 4,
                room: 5,
                message: "Incredible tour! The amenities were top-notch and very comfortable.",
                averageGrade: 0,
                createdAt: "2023-09-10",
                tourId: 3
              },
              {
                name_user: "Fiona Gallagher",
                email_user: "fionagallagher@example.com",
                services: 3,
                locations: 4,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 4,
                message: "Great locations but average amenities. The price was reasonable.",
                averageGrade: 0,
                createdAt: "2023-09-20",
                tourId: 3
              },
              {
                name_user: "George Martin",
                email_user: "georgemartin@example.com",
                services: 4,
                locations: 5,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Had a wonderful time on this tour! The food was delightful.",
                averageGrade: 0,
                createdAt: "2023-10-05",
                tourId: 4
              },
              {
                name_user: "Hannah Baker",
                email_user: "hannahbaker@example.com",
                services: 5,
                locations: 4,
                amenities: 4,
                prices: 3,
                food: 3,
                room: 4,
                message: "A great tour overall. I loved the locations, and the services were good.",
                averageGrade: 0,
                createdAt: "2023-10-15",
                tourId: 4
              },
              {
                name_user: "Ian Malcolm",
                email_user: "ianmalcolm@example.com",
                services: 4,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 4,
                message: "The locations were stunning, but the prices could be better.",
                averageGrade: 0,
                createdAt: "2023-11-01",
                tourId: 5
              },
              {
                name_user: "Julia Child",
                email_user: "juliachild@example.com",
                services: 3,
                locations: 4,
                amenities: 5,
                prices: 3,
                food: 4,
                room: 3,
                message: "Good food and friendly staff, but the overall experience was average.",
                averageGrade: 0,
                createdAt: "2023-11-15",
                tourId: 5
              },
              {
                name_user: "Kyle Rayner",
                email_user: "kylerayner@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 4,
                message: "An unforgettable adventure with beautiful sights and great service.",
                averageGrade: 0,
                createdAt: "2023-12-05",
                tourId: 6
              },
              {
                name_user: "Laura Croft",
                email_user: "lauracroft@example.com",
                services: 4,
                locations: 4,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 4,
                message: "The tour was fantastic, but the price was a bit steep.",
                averageGrade: 0,
                createdAt: "2023-12-10",
                tourId: 6
              },
              {
                name_user: "Mike Wazowski",
                email_user: "mikewazowski@example.com",
                services: 3,
                locations: 5,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 3,
                message: "Good tour overall, but could improve on amenities. The food was great.",
                averageGrade: 0,
                createdAt: "2024-01-12",
                tourId: 7
              },
              {
                name_user: "Nina Williams",
                email_user: "ninawilliams@example.com",
                services: 4,
                locations: 4,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 4,
                message: "A nice experience, with good locations and services.",
                averageGrade: 0,
                createdAt: "2024-01-25",
                tourId: 7
              },
              {
                name_user: "Oscar Isaac",
                email_user: "oscarisaac@example.com",
                services: 5,
                locations: 5,
                amenities: 5,
                prices: 3,
                food: 4,
                room: 4,
                message: "Fantastic tour! The amenities were excellent, and the staff was friendly.",
                averageGrade: 0,
                createdAt: "2024-02-15",
                tourId: 8
              },
              {
                name_user: "Paula Patton",
                email_user: "paulapatton@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Good overall experience, but some amenities need improvement.",
                averageGrade: 0,
                createdAt: "2024-02-25",
                tourId: 8
              },
              {
                name_user: "Quinn Fabray",
                email_user: "quinnfabray@example.com",
                services: 4,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 3,
                room: 4,
                message: "Great tour! Beautiful locations, though the food was average.",
                averageGrade: 0,
                createdAt: "2024-03-12",
                tourId: 9
              },
              {
                name_user: "Rick Sanchez",
                email_user: "ricksanchez@example.com",
                services: 5,
                locations: 4,
                amenities: 5,
                prices: 2,
                food: 4,
                room: 4,
                message: "An interesting tour with great amenities and good food.",
                averageGrade: 0,
                createdAt: "2024-03-25",
                tourId: 9
              },
              {
                name_user: "Samantha Carter",
                email_user: "samanthacarter@example.com",
                services: 3,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Good value for the tour, though some amenities could use improvement.",
                averageGrade: 0,
                createdAt: "2024-04-10",
                tourId: 10
              },
              {
                name_user: "Tom Hanks",
                email_user: "tomhanks@example.com",
                services: 4,
                locations: 4,
                amenities: 5,
                prices: 2,
                food: 3,
                room: 5,
                message: "The tour was great, but the prices were a bit high for what was offered.",
                averageGrade: 0,
                createdAt: "2024-04-20",
                tourId: 10
              },
              {
                name_user: "Sam Oliver",
                email_user: "samoliver@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Good value for the tour, though some of the amenities could be improved. The food was fantastic.",
                averageGrade: 0,
                createdAt: "2024-03-19",
                tourId: 11
              },
              {
                name_user: "Tina Roberts",
                email_user: "tinaroberts@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Excellent tour with beautiful locations and great services. Highly recommend!",
                averageGrade: 0,
                createdAt: "2023-07-03",
                tourId: 11
              },
              {
                name_user: "Uma Clarke",
                email_user: "umaclarke@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 3,
                message: "Good tour, though the amenities could be improved. The food and locations were solid.",
                averageGrade: 0,
                createdAt: "2024-06-05",
                tourId: 12
              },
              {
                name_user: "Victor Price",
                email_user: "victorprice@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Fantastic experience with top-notch services and beautiful locations. Highly recommend!",
                averageGrade: 0,
                createdAt: "2024-05-24",
                tourId: 12
              },
              {
                name_user: "Wendy Bell",
                email_user: "wendybell@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 5,
                room: 4,
                message: "Good tour overall, though the amenities could use improvement. The food was fantastic.",
                averageGrade: 0,
                createdAt: "2023-11-29",
                tourId: 13
              },
              {
                name_user: "Xavier Johnson",
                email_user: "xavierjohnson@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 4,
                message: "Amazing tour with stunning locations and top-notch services. The prices were a bit steep.",
                averageGrade: 0,
                createdAt: "2024-03-25",
                tourId: 13
              },
              {
                name_user: "Yara Knight",
                email_user: "yaraknight@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 5,
                room: 4,
                message: "Good tour overall, though the amenities could be improved. The food was fantastic.",
                averageGrade: 0,
                createdAt: "2023-10-12",
                tourId: 14
              },
              {
                name_user: "Zack Martin",
                email_user: "zackmartin@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 4,
                room: 5,
                message: "Fantastic tour with beautiful locations and top-notch services. The prices were a bit steep.",
                averageGrade: 0,
                createdAt: "2024-02-27",
                tourId: 14
              },
              {
                name_user: "Adam Cooper",
                email_user: "adamcooper@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 3,
                message: "Good tour, though the amenities could be improved. The food and services were solid.",
                averageGrade: 0,
                createdAt: "2024-04-12",
                tourId: 15
              },
              {
                name_user: "Betty Harris",
                email_user: "bettyharris@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 4,
                message: "Amazing tour with top-notch services and stunning locations. The prices were a bit high.",
                averageGrade: 0,
                createdAt: "2023-06-18",
                tourId: 15
              },
              {
                name_user: "Carl Sanders",
                email_user: "carlsanders@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 5,
                room: 4,
                message: "Good tour overall, though the amenities could use improvement. The food was fantastic.",
                averageGrade: 0,
                createdAt: "2024-01-04",
                tourId: 16
              },
              {
                name_user: "Diane Bennett",
                email_user: "dianebennett@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 4,
                room: 4,
                message: "Fantastic tour with stunning locations and top-notch services. The prices were a bit steep.",
                averageGrade: 0,
                createdAt: "2023-09-06",
                tourId: 16
              },
              {
                name_user: "Eddie Brooks",
                email_user: "eddiebrooks@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 5,
                room: 4,
                message: "Good tour overall, though the amenities could use improvement. The food was fantastic.",
                averageGrade: 0,
                createdAt: "2024-04-30",
                tourId: 17
              },
              {
                name_user: "Fay Morrison",
                email_user: "faymorrison@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Amazing experience with top-notch services and beautiful locations.",
                averageGrade: 0,
                createdAt: "2023-07-25",
                tourId: 17
              },
              {
                name_user: "Gina Perez",
                email_user: "ginaperez@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 5,
                room: 4,
                message: "Good tour overall, though the amenities could use improvement. The food was fantastic.",
                averageGrade: 0,
                createdAt: "2023-12-05",
                tourId: 18
              },
              {
                name_user: "Hank Johnson",
                email_user: "hankjohnson@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Fantastic tour with top-notch services and beautiful locations. Highly recommend!",
                averageGrade: 0,
                createdAt: "2024-03-14",
                tourId: 18
              },
              {
                name_user: "Ivy Wilson",
                email_user: "ivywilson@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Good tour with excellent food. The amenities could be improved.",
                averageGrade: 0,
                createdAt: "2023-10-30",
                tourId: 19
              },
              {
                name_user: "Jackie Brown",
                email_user: "jackiebrown@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Amazing experience with stunning locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2024-02-12",
                tourId: 19
              },
              {
                name_user: "Karen White",
                email_user: "karenwhite@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 3,
                message: "Good tour overall, though the amenities could be improved. The food was great.",
                averageGrade: 0,
                createdAt: "2023-11-03",
                tourId: 20
              },
              {
                name_user: "Liam Martin",
                email_user: "liammartin@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 5,
                message: "Fantastic tour with beautiful locations and top-notch services. Highly recommend!",
                averageGrade: 0,
                createdAt: "2024-04-19",
                tourId: 20
              },
              {
                name_user: "Mia Scott",
                email_user: "miascott@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 3,
                message: "Good tour, though the amenities could be better. The food was excellent.",
                averageGrade: 0,
                createdAt: "2023-06-29",
                tourId: 21
              },
              {
                name_user: "Nina Wilson",
                email_user: "ninawilson@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 4,
                message: "Amazing experience with beautiful locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2023-09-18",
                tourId: 21
              },
              {
                name_user: "Oliver Clark",
                email_user: "oliverclark@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 4,
                message: "Good tour overall, though the amenities could be improved. The food was great.",
                averageGrade: 0,
                createdAt: "2024-05-27",
                tourId: 22
              },
              {
                name_user: "Paula Johnson",
                email_user: "paulajohnson@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 5,
                room: 5,
                message: "Fantastic tour with beautiful locations and top-notch services. Highly recommend!",
                averageGrade: 0,
                createdAt: "2023-12-27",
                tourId: 22
              },
              {
                name_user: "Quincy Adams",
                email_user: "quincyadams@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Good tour with excellent food. The amenities could be improved.",
                averageGrade: 0,
                createdAt: "2024-01-16",
                tourId: 23
              },
              {
                name_user: "Rachel Lee",
                email_user: "rachellee@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Amazing tour with stunning locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2023-10-06",
                tourId: 23
              },
              {
                name_user: "Sam White",
                email_user: "samwhite@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Good tour overall, though the amenities could be improved. The food was great.",
                averageGrade: 0,
                createdAt: "2024-03-07",
                tourId: 24
              },
              {
                name_user: "Tina Brown",
                email_user: "tinabrown@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 5,
                message: "Fantastic experience with stunning locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2023-05-13",
                tourId: 24
              },
              {
                name_user: "Uma Green",
                email_user: "umagreen@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 4,
                room: 3,
                message: "Good tour overall, though the amenities could be better. The food was excellent.",
                averageGrade: 0,
                createdAt: "2023-07-10",
                tourId: 25
              },
              {
                name_user: "Victor Brown",
                email_user: "victorbrown@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Amazing experience with beautiful locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2024-04-10",
                tourId: 25
              },
              {
                name_user: "Wendy Adams",
                email_user: "wendyadams@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 4,
                message: "Good tour overall, though the amenities could be improved. The food was great.",
                averageGrade: 0,
                createdAt: "2023-08-20",
                tourId: 26
              },
              {
                name_user: "Xavier Martin",
                email_user: "xaviermartin@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 4,
                room: 5,
                message: "Fantastic tour with beautiful locations and top-notch services. Highly recommend!",
                averageGrade: 0,
                createdAt: "2023-11-15",
                tourId: 26
              },
              {
                name_user: "Yara White",
                email_user: "yarawhite@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 5,
                room: 4,
                message: "Good tour overall, though the amenities could be improved. The food was great.",
                averageGrade: 0,
                createdAt: "2024-02-23",
                tourId: 27
              },
              {
                name_user: "Zack Brown",
                email_user: "zackbrown@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 4,
                room: 5,
                message: "Amazing tour with beautiful locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2023-10-16",
                tourId: 27
              },
              {
                name_user: "Adam Green",
                email_user: "adamgreen@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 3,
                message: "Good tour overall, though the amenities could be better. The food was solid.",
                averageGrade: 0,
                createdAt: "2024-04-14",
                tourId: 28
              },
              {
                name_user: "Betty Johnson",
                email_user: "bettyjohnson@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 2,
                food: 5,
                room: 5,
                message: "Amazing experience with beautiful locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2023-09-23",
                tourId: 28
              },
              {
                name_user: "Carl Brown",
                email_user: "carlbrown@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 4,
                room: 3,
                message: "Good tour overall, though the amenities could use improvement. The food was great.",
                averageGrade: 0,
                createdAt: "2023-11-27",
                tourId: 29
              },
              {
                name_user: "Diane White",
                email_user: "dianewhite@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 5,
                room: 5,
                message: "Amazing tour with stunning locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2024-03-11",
                tourId: 29
              },
              {
                name_user: "Eddie Green",
                email_user: "eddiegreen@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 4,
                message: "Good tour overall, though the amenities could be improved. The food was solid.",
                averageGrade: 0,
                createdAt: "2023-10-04",
                tourId: 30
              },
              {
                name_user: "Fay Brown",
                email_user: "faybrown@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 5,
                room: 5,
                message: "Fantastic tour with beautiful locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2024-02-08",
                tourId: 30
              },
              {
                name_user: "Gina White",
                email_user: "ginawhite@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 4,
                food: 4,
                room: 4,
                message: "Good tour overall, though the amenities could be improved. The food was great.",
                averageGrade: 0,
                createdAt: "2023-06-24",
                tourId: 31
              },
              {
                name_user: "Hank Green",
                email_user: "hankgreen@example.com",
                services: 5,
                locations: 5,
                amenities: 4,
                prices: 3,
                food: 5,
                room: 4,
                message: "Amazing experience with beautiful locations and top-notch services.",
                averageGrade: 0,
                createdAt: "2024-03-02",
                tourId: 31
              },
              {
                name_user: "Ivy Brown",
                email_user: "ivybrown@example.com",
                services: 4,
                locations: 4,
                amenities: 3,
                prices: 3,
                food: 4,
                room: 3,
                message: "Good tour overall, though the amenities could use improvement. The food was great.",
                averageGrade: 0,
                createdAt: "2024-04-07",
                tourId: 32
              }
        ])
    }catch(error){
        console.error(error)
    }
}

export default addReviews()